import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Birds Detector",
  description: "Generated by Next JS 14"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <h1 style={{textAlign:"center"}}>Next JS With Python</h1>
      <h2>Integrated Deep Learning</h2>
      <div className="container">
        <a href="http://localhost:3000/">Refresh</a>
      </div>
      {children}      
      </body>
    </html>
  );
}
